### ISSUE TITLE
Ошибка при начале генерации промокодов

### ISSUE THREAD

**Issue by butalex11** [OxFF00FF/Hamster_Mayhem#10]
Хотите применить промокоды после получения?
Y(да) / Enter(Нет): Y

Количество промокодов для всех игр Enter(по умолчанию 1): 4

`Bike Ride 3D` · Генерируется промокодов: 4 ~ 00:05:40
🚴  Катаемся на велосипедах, чтобы вам не пришлось)

`Chain Cube 2048` · Генерируется промокодов: 4 ~ 00:02:20
🎲  Гоняем кубы за вас

`My Clone Army` · Генерируется промокодов: 4 ~ 00:13:53
🎮  Проходим клонов вместо вас

`Train Miner` · Генерируется промокодов: 4 ~ 00:04:00
🚂  Проходим поезда, чтобы вам не пришлось)

`Merge Away` · Генерируется промокодов: 4 ~ 00:02:20
💎  Объединяем предметы вместо вас

`Twerk Race` · Генерируется промокодов: 4 ~ 00:03:20
🏃  Бежим куда-то

`Polysphere` · Генерируется промокодов: 4 ~ 00:00:51
🐋  Восстанавливаем изображения за вас

`Mud Racing` · Генерируется промокодов: 4 ~ 00:06:40
🚙  Едем за ключами вместо вас

`Mow and Trim` · Генерируется промокодов: 4 ~ 00:06:40
🌾  Косим траву
| ▱▱▱▱▱▱▱ | 2024-08-26 09:10:03,154 - root - ERROR |  🚫  Произошла ошибка: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://api.gamepromo.io/promo/login-client'
Traceback (most recent call last):
  File "/root/Hamsters_mayhem/main.py", line 26, in <module>
    handle_main_menu_choice(choice)
  File "/root/Hamsters_mayhem/Src/Menu.py", line 187, in handle_main_menu_choice
    handle_playground_menu()
  File "/root/Hamsters_mayhem/Src/Menu.py", line 377, in handle_playground_menu
    asyncio.run(genetare_for_all_games())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/Hamsters_mayhem/Src/Menu.py", line 411, in genetare_for_all_games
    await asyncio.gather(*tasks)
  File "/root/Hamsters_mayhem/Src/Hamster.py", line 747, in get_promocodes
    promocodes = await __start_generate(count)
  File "/root/Hamsters_mayhem/Src/Hamster.py", line 742, in __start_generate
    keys = await asyncio.gather(*tasks)
  File "/root/Hamsters_mayhem/Src/Hamster.py", line 707, in __key_generation
    client_token = await __get_client_token(session, client_id)
  File "/root/Hamsters_mayhem/Src/Hamster.py", line 664, in __get_client_token
    data = await response.json()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_reqrep.py", line 1199, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://api.gamepromo.io/promo/login-client'

  | main.py - <module>() - 30

**Comment by OxFF00FF** [comment]
слишком большое количество для всех игр выбираете. 
там лимит примерно 20 запросов.
и из за большого количества игр, оптимально будет 1-2 ключа для всех игр.
даже для 2 может не для всех сгенерить. я тестировал на 1, работало нормально
