### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andrei4ik1997** [OxFF00FF/Hamster_Mayhem#27]
Hamster_Mayhem\venv\Lib\site-packages\pydantic\main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 5 validation errors for Config
HAMSTER_TOKEN_3
  Field required [type=missing, input_value={'HAMSTER_TOKEN_1': 'Bear...D': '', 'GROUP_URL': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
CHAT_ID
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing
BOT_LOGS_GROUP_ID
  Field required [type=missing, input_value={'HAMSTER_TOKEN_1': 'Bear...D': '', 'GROUP_URL': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
TELEGRAM_API_ID
  Field required [type=missing, input_value={'HAMSTER_TOKEN_1': 'Bear...D': '', 'GROUP_URL': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
TELEGRAM_API_HASH
  Field required [type=missing, input_value={'HAMSTER_TOKEN_1': 'Bear...D': '', 'GROUP_URL': ''}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by pekatron9000** [comment]
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\main.py", line 4, in <module>
    from Src.Handlers import handle_main_menu_choice, handle_main_menu_not_logged_choice
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\Src\Handlers.py", line 7, in <module>
    from Src.Hamster_bot import HamsterUltimate
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\Src\Hamster_bot.py", line 6, in <module>
    from config import app_config
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\config\__init__.py", line 1, in <module>
    from .config import app_config
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\config\config.py", line 25, in <module>
    app_config = Config()
                 ^^^^^^^^
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\venv\Lib\site-packages\pydantic_settings\main.py", line 152, in __init__
    super().__init__(
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\venv\Lib\site-packages\pydantic\main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
CHAT_ID
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing

[процесс завершил работу с кодом 1 (0x00000001)]
Теперь вы можете закрыть этот терминал с помощью клавиш CTRL+D. Или нажмите клавишу ВВОД для перезапуска.

**Comment by Lastnet0709** [comment]
> Traceback (most recent call last): File "C:\Users\Admin\Desktop\Hamster_Mayhem\main.py", line 4, in from Src.Handlers import handle_main_menu_choice, handle_main_menu_not_logged_choice File "C:\Users\Admin\Desktop\Hamster_Mayhem\Src\Handlers.py", line 7, in from Src.Hamster_bot import HamsterUltimate File "C:\Users\Admin\Desktop\Hamster_Mayhem\Src\Hamster_bot.py", line 6, in from config import app_config File "C:\Users\Admin\Desktop\Hamster_Mayhem\config__init__.py", line 1, in from .config import app_config File "C:\Users\Admin\Desktop\Hamster_Mayhem\config\config.py", line 25, in app_config = Config() ^^^^^^^^ File "C:\Users\Admin\Desktop\Hamster_Mayhem\venv\Lib\site-packages\pydantic_settings\main.py", line 152, in **init** super().**init**( File "C:\Users\Admin\Desktop\Hamster_Mayhem\venv\Lib\site-packages\pydantic\main.py", line 212, in **init** validated_self = self.**pydantic_validator**.validate_python(data, self_instance=self) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ pydantic_core._pydantic_core.ValidationError: 1 validation error for Config CHAT_ID Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='', input_type=str] For further information visit https://errors.pydantic.dev/2.9/v/int_parsing
> 
> [процесс завершил работу с кодом 1 (0x00000001)] Теперь вы можете закрыть этот терминал с помощью клавиш CTRL+D. Или нажмите клавишу ВВОД для перезапуска.

got same error

**Comment by OxFF00FF** [comment]
update code and dependencies
`pip isntall -r requirements.txt`
if there are any more errors, please let me know

**Comment by pekatron9000** [comment]
начисто раскаковываю зип репозитория > install.bat > отдельно ещё обновляю зависимости через pip install -r requirements.txt, но всё равно получаю это:
питон версии 3.11.9

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\main.py", line 4, in <module>
    from Src.Handlers import handle_main_menu_choice, handle_main_menu_not_logged_choice
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\Src\Handlers.py", line 8, in <module>
    from Src.Hamster import HamsterKombatClicker
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\Src\Hamster.py", line 20, in <module>
    from config import app_config
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\config\__init__.py", line 1, in <module>
    from .config import app_config
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\config\config.py", line 26, in <module>
    app_config = Config()
                 ^^^^^^^^
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\venv\Lib\site-packages\pydantic_settings\main.py", line 152, in __init__
    super().__init__(
  File "C:\Users\Admin\Desktop\Hamster_Mayhem\venv\Lib\site-packages\pydantic\main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
CHAT_ID
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing

[процесс завершил работу с кодом 1 (0x00000001)]
Теперь вы можете закрыть этот терминал с помощью клавиш CTRL+D. Или нажмите клавишу ВВОД для перезапуска.

**Comment by OxFF00FF** [comment]
Кажется у тебя chat_id с кавычками,  либо какую-то другую переменную неверно указал

**Comment by pekatron9000** [comment]
хз, ничего кроме хамстер токена не трогал в .env файле
![image](https://github.com/user-attachments/assets/38c798a9-9c33-4051-9808-f12c9a8164fd)

**Comment by OxFF00FF** [comment]
Кажется у тебя chat_id с кавычками,  либо какую-то другую переменную неверно указал 

Дожно работать.  Попробуй все строки кроме токена закомментировать # в начале строки.

**Comment by pekatron9000** [comment]
закомментил всё кроме токена, запустил START_WT.bat, на секунду появился логотип хамстер майхем, но далее всё равно ошибка. что же я делаю не так :С
![image](https://github.com/user-attachments/assets/fa24483d-c34c-4e93-a0a7-c3b611272465)

**Comment by OxFF00FF** [comment]
Понятно,  попробуй сейчас обновить и запустить

**Comment by pekatron9000** [comment]
заработало! спасибо большое
![image](https://github.com/user-attachments/assets/e1e8d8ef-1e4b-4ce2-af2b-2a7982b06c13)

**Comment by pekatron9000** [comment]
так у меня никакого chat_id нету)
![image](https://github.com/user-attachments/assets/9d4b4e0a-22da-4259-add7-ce471f7f9f38)

**Comment by pekatron9000** [comment]
как в прошлый раз, закомментил всё кроме хамстер токена, и вот такой результат
![image](https://github.com/user-attachments/assets/32d507ee-2d01-4362-acf8-485c61f4a3f2)

**Comment by Lastnet0709** [comment]
> как в прошлый раз, закомментил всё кроме хамстер токена, и вот такой результат ![image](https://private-user-images.githubusercontent.com/7441100/371289573-32d507ee-2d01-4362-acf8-485c61f4a3f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczODExMDcsIm5iZiI6MTcyNzM4MDgwNywicGF0aCI6Ii83NDQxMTAwLzM3MTI4OTU3My0zMmQ1MDdlZS0yZDAxLTQzNjItYWNmOC00ODVjNjFmNGEzZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMjAwMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNlZDEzNzIzZDJhNGQyZWE4ZDUzZGQxZTkwMmZmOTM3ZTAxM2M3ZGJmOGRjMDEzZTBmMmE5YmU3NTQyNzQyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YksIq6Stu50Djtd_ECJvM_oBMrYt9O0Nou7OGH7yWoA)

Change 
`selected_token = os.getenv('SELECTED', app_config.HAMSTER_TOKEN_2)`
To 
`selected_token = os.getenv('SELECTED', app_config.HAMSTER_TOKEN_1)`
In Src/HamsterClient.py

It's work for me
