### ISSUE TITLE
Error after new update 

### ISSUE THREAD

**Issue by Lastnet0709** [OxFF00FF/Hamster_Mayhem#29]
Before new update and use last [Commit ](https://github.com/OxFF00FF/Hamster_Mayhem/commit/b7dafd309a7937f781961ff66b16ba416f4be57c) it's works well even if it's only for doing tasks, auto upgrading cards and applying keys
```
Starting...
Traceback (most recent call last):
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "\Hamster_Mayhem\main.py", line 4, in <module>
    from Src.Handlers import handle_main_menu_choice, handle_main_menu_not_logged_choice
  File "\Hamster_Mayhem\Src\Handlers.py", line 7, in <module>
    from Src.Hamster_ultimate import HamsterUltimate
  File "\Hamster_Mayhem\Src\Hamster_ultimate.py", line 8, in <module>
    from Src.HamsterClient import client
  File "\Hamster_Mayhem\Src\HamsterClient.py", line 5, in <module>
    client = HamsterKombatClicker(hamster_token=app_config.HAMSTER_TOKEN_1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\Src\Hamster.py", line 38, in __init__
    init_db()
  File "\Hamster_Mayhem\database\queries.py", line 13, in init_db
    Base.metadata.create_all(engine)
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\sql\schema.py", line 5868, in create_all
    bind._run_ddl_visitor(
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3252, in _run_ddl_visitor
    with self.begin() as conn:
  File "C:\Users\Mamans07\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3242, in begin
    with self.connect() as conn:
         ^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3278, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2442, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 900, in __connect
    with util.safe_reraise():
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Hamster_Mayhem\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 621, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by Lastnet0709** [comment]
I think you forgot to change this value
```
🔄  Next balance afternext balance after: 01:48:43
Exception in thread Thread-1 (process_balance):
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "\Hamster_Mayhem\Src\Hamster_ultimate.py", line 35, in process_balance
    f"💰  Баланс: {info['balanceCoins']:,} \n" \
                  ~~~~^^^^^^^^^^^^^^^^
KeyError: 'balanceCoins'
```

And this error appeared after my account received all the keys.
```
ℹ️  All promocodes recieved today
Exception in thread Thread-3 (process_promocodes):
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "\Hamster_Mayhem\Src\Hamster_ultimate.py", line 148, in process_promocodes
    games, remain = client.minigames_for_generate()
    ^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

**Another small problem**

- The language cannot be changed to 'EN' even after changing it and restarting the bot.
- Sending the command "." from the sub menu to return to the main menu does not immediately display the main menu, I have to send the command "m" first to display it.

**Comment by OxFF00FF** [comment]
>Sending the command "." from the sub menu to return to the main menu does not immediately display the main menu, I have to send the command "m" first to display it.

that's right, you go to the main menu, it just doesn't print again
When you enter commands, the available commands and which menu you are in are indicated in parentheses

![image](https://github.com/user-attachments/assets/6cb4db86-3b98-4a5f-af72-8ec7a84ec386)


for change lang now, you need specify it in .env file. if not specify, default will be en
LANG="en"

**Comment by Lastnet0709** [comment]
Works as before and this is the only thing still showing after the latest update. not a problem as long as the feature runs normally.
```
Exception in thread Thread-1 (process_balance):
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "\Hamster_Mayhem\Src\Hamster_ultimate.py", line 36, in process_balance
    f"💰  {localized_text('balance')}: {info[f'balance{currency}']:,} \n" \
                                       ~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'balanceDiamonds'
```

**Comment by Lastnet0709** [comment]
**Just a report after the update xD** Use last [Commit](https://github.com/OxFF00FF/Hamster_Mayhem/commit/76823b2eab57f11d7ff2e4e9844a0f31cc9ede35)

- I didn't activate the "Send to group" feature but this error appeared

 `🚫  Error_occured: 400 Client Error: Bad Request for url: https://api.telegram.org/bot"Token Bot"/sendMessage`

- I think the output for "All promocodes received today" looks better in the previous version which showed a list of game names


 ![image](https://github.com/user-attachments/assets/d11c6b38-908f-4312-bbdb-46459149ead4)
