### ISSUE TITLE
Ошибка при запуске 

### ISSUE THREAD

**Issue by butalex11** [OxFF00FF/Hamster_Mayhem#8]
2024-08-23 11:46:04,976 - root - ERROR |  🚫  HTTP ошибка: 422 Client Error: Unprocessable Entity for url: https://api.hamsterkombatgame.io/auth/account-info  | Hamster.py - login() - 847
2024-08-23 11:46:05,239 - root - ERROR |  🚫  HTTP ошибка: 422 Client Error: Unprocessable Entity for url: https://api.hamsterkombatgame.io/clicker/upgrades-for-buy  | Hamster.py - _activity_cooldowns() - 214
Traceback (most recent call last):
  File "/root/Hamsters_mayhem/main.py", line 21, in <module>
    main_menu()
  File "/root/Hamsters_mayhem/Src/Menu.py", line 78, in main_menu
    for activity in activities:
TypeError: 'NoneType' object is not iterable

**Comment by edwardtich1** [comment]
это бывает. запустить позже

**Comment by OxFF00FF** [comment]
вы hamster token верно указали?

**Comment by edwardtich1** [comment]
Будет обновление проекта для новых игр?

**Comment by edwardtich1** [comment]
2024-08-23 14:39:59,574 - root - ERROR |  🚫  HTTP ошибка: 422 Client Error: Unprocessable Entity for url: https://api.hamsterkombatgame.io/auth/account-info  | Hamster.py - login() - 832
2024-08-23 14:40:00,034 - root - ERROR |  🚫  HTTP ошибка: 422 Client Error: Unprocessable Entity for url: https://api.hamsterkombatgame.io/clicker/upgrades-for-buy  | Hamster.py - _activity_cooldowns() - 215
Traceback (most recent call last):
  File "C:\new_bot\Hamster_Mayhem\main.py", line 21, in <module>
    main_menu()
  File "C:\new_bot\Hamster_Mayhem\Src\Menu.py", line 78, in main_menu
    for activity in activities:
TypeError: 'NoneType' object is not iterable

такая же ошибка

**Comment by butalex11** [comment]
> вы hamster token верно указали?

так предыдущие версии норм работали, а на этой ошибка. токен не трогал в файле

**Comment by OxFF00FF** [comment]
Можете пока бота использовать. Там сейчас все игры есть

**Comment by edwardtich1** [comment]
Какого бота?

**Comment by OxFF00FF** [comment]
Бот в телеграме, описании есть ссылка

**Comment by edwardtich1** [comment]
Меня генераторы в меньшей мере интересуют.  Их уже десятки

**Comment by OxFF00FF** [comment]
Я обновил формат в .env
Из за этого не работает 
https://github.com/OxFF00FF/Hamster_Mayhem/blob/master/.env.example

**Comment by edwardtich1** [comment]
у меня нет в этом файле вообще упоминаний о телеграм

**Comment by edwardtich1** [comment]
если тут код хотя бы лькрытый то из бота все что угодно может улететь на сторону. жаль. хороший был проект

**Comment by OxFF00FF** [comment]
> если тут код хотя бы открытый то из бота все что угодно может улететь на сторону. жаль. хороший был проект

Проект так же остался,  и еще дополнительно бота делаю

**Comment by edwardtich1** [comment]
это хорошо но он не работает)

**Comment by edwardtich1** [comment]
```
| ▰▰▱▱▱▱▱ | 2024-08-23 20:13:26,656 - root - ERROR |  🚫  Произошла ошибка: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://api.gamepromo.io/promo/login-client'
Traceback (most recent call last):
  File "C:\new_bot\Hamster_Mayhem\main.py", line 26, in <module>
    handle_main_menu_choice(choice)
  File "C:\new_bot\Hamster_Mayhem\Src\Menu.py", line 187, in handle_main_menu_choice
    handle_playground_menu()
  File "C:\new_bot\Hamster_Mayhem\Src\Menu.py", line 377, in handle_playground_menu
    asyncio.run(genetare_for_all_games())
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\new_bot\Hamster_Mayhem\Src\Menu.py", line 411, in genetare_for_all_games
    await asyncio.gather(*tasks)
  File "C:\new_bot\Hamster_Mayhem\Src\Hamster.py", line 747, in get_promocodes
    promocodes = await __start_generate(count)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\new_bot\Hamster_Mayhem\Src\Hamster.py", line 742, in __start_generate
    keys = await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\new_bot\Hamster_Mayhem\Src\Hamster.py", line 707, in __key_generation
    client_token = await __get_client_token(session, client_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\new_bot\Hamster_Mayhem\Src\Hamster.py", line 664, in __get_client_token
    data = await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\new_bot\Hamster_Mayhem\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1199, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://api.gamepromo.io/promo/login-client'

  | main.py - <module>() - 30
```

**Comment by OxFF00FF** [comment]
Это на их стороне ошибка. Иногда возникает во время генерации ,  просто еще раз начните
